language: cpp
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - graphviz
      - build-essential
      - libcairo2-dev
      - libgraphicsmagick1-dev
      - libpng-dev
      - g++-7
    env:
      - MATRIX_EVAL="CC=clang-7.0 && CXX=clang++-7.0"

script:
  - sudo rm /usr/bin/g++
  - sudo ln -s /usr/bin/g++-7 /usr/bin/g++
  - g++ --version
  - mkdir -p build
  - cd build
  - cmake ..
